apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: mood-analyzer-rabbitmq-claim
  annotations: {}
  labels:
    app.kubernetes.io/part-of: mood-analyzer
    apps.tanzu.vmware.com/workload-type: dekt-worker
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-analyzer
spec:
  name: rabbitmq-claim
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: reading-queue
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: mood-analyzer

